"""initial migration

Revision ID: 147c6e03f86b
Revises: 
Create Date: 2026-02-04 17:13:12.300963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147c6e03f86b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('puppy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('puppy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toy')
    op.drop_table('owner')
    op.drop_table('puppy')
    # ### end Alembic commands ###
